config/routes.rb
ProjetApp::Application.routes.draw do
  get 'home' => 'pages#home' , as: 'home'
  get 'about' => 'pages#about' , as: 'about'
  get 'contact' => 'pages#contact' , as: 'contact'
  get 'aide' => 'pages#aide' , as: 'aide'
 
  
  resources :anecdotes

  resources :personnes

  resources :scenes

  resources :chapitres do
	get 'delete' => 'chapitre#delete' , as: 'delete'
  end
	
 
  
  root to: 'pages#home'
  
  
end

app/models/personne.rb
# == Schema Information
#
# Table name: personnes
#
#  id         :integer          not null, primary key
#  nom        :string(255)
#  prenom     :string(255)
#  numero     :integer
#  scene_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Personne < ActiveRecord::Base
	has_many :scenes, :dependent => :destroy

 	validates :numero, :presence => true,
			   :uniqueness => true
		  
	validates :nom, :presence => true,
			  :length => { :maximum => 30 }

	validates :prenom, :presence => true,
			  :length => { :maximum => 30 }
			  
end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render action: 'show', status: :created, location: @personne }
      else
        format.html { render action: 'new' }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:nom, :prenom, :numero, :scene_id)
    end
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/personnes/_form.html.erb
<%= form_for(@personne) do |f| %>
  <% if @personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% @personne.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :scene_id %><br>
    <%= f.number_field :scene_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnes/edit.html.erb
<h1>Editing personne</h1>

<%= render 'form' %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

app/views/personnes/index.html.erb
<h1>Listes des personnes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Numero</th>
      <th>Scene</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.nom %></td>
        <td><%= personne.prenom %></td>
        <td><%= personne.numero %></td>
        <td><%= personne.scene_id %></td>
        <td><%= link_to 'Voir', personne %></td>
        <td><%= link_to 'Modifier', edit_personne_path(personne) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter une Personne', new_personne_path %>

app/views/personnes/new.html.erb
<h1>New personne</h1>

<%= render 'form' %>

<%= link_to 'Back', personnes_path %>

app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @personne.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @personne.prenom %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @personne.numero %>
</p>

<p>
  <strong>Scene:</strong>
  <%= @personne.scene_id %>
</p>

<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>