config/routes.rb
ProjetApp::Application.routes.draw do
  get 'home' => 'pages#home' , as: 'home'
  get 'about' => 'pages#about' , as: 'about'
  get 'contact' => 'pages#contact' , as: 'contact'
  get 'aide' => 'pages#aide' , as: 'aide'
 
  
  resources :anecdotes

  resources :personnes

  resources :scenes

  resources :chapitres do
	get 'delete' => 'chapitre#delete' , as: 'delete'
  end
	
 
  
  root to: 'pages#home'
  
  
end

app/models/anecdote.rb
# == Schema Information
#
# Table name: anecdotes
#
#  id          :integer          not null, primary key
#  sujet       :string(255)
#  theme       :string(255)
#  texte       :text
#  chapitre_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Anecdote < ActiveRecord::Base
	belongs_to :chapitre 
	
  	validates :theme, :presence => true
	validates :chapitre_id, :presence => true		  
	validates :sujet, :presence => true,
			  :length => { :maximum => 30 },
			  :uniqueness => true
end

app/controllers/anecdotes_controller.rb
class AnecdotesController < ApplicationController
  before_action :set_anecdote, only: [:show, :edit, :update, :destroy]

  # GET /anecdotes
  # GET /anecdotes.json
  def index
    @anecdotes = Anecdote.all
  end

  # GET /anecdotes/1
  # GET /anecdotes/1.json
  def show
  end

  # GET /anecdotes/new
  def new
    @anecdote = Anecdote.new
  end

  # GET /anecdotes/1/edit
  def edit
  end

  # POST /anecdotes
  # POST /anecdotes.json
  def create
    @anecdote = Anecdote.new(anecdote_params)

    respond_to do |format|
      if @anecdote.save
        format.html { redirect_to @anecdote, notice: 'Anecdote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @anecdote }
      else
        format.html { render action: 'new' }
        format.json { render json: @anecdote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anecdotes/1
  # PATCH/PUT /anecdotes/1.json
  def update
    respond_to do |format|
      if @anecdote.update(anecdote_params)
        format.html { redirect_to @anecdote, notice: 'Anecdote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @anecdote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anecdotes/1
  # DELETE /anecdotes/1.json
  def destroy
    @anecdote.destroy
    respond_to do |format|
      format.html { redirect_to anecdotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anecdote
      @anecdote = Anecdote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anecdote_params
      params.require(:anecdote).permit(:sujet, :theme, :texte, :chapitre_id)
    end
end

app/helpers/anecdotes_helper.rb
module AnecdotesHelper
end

app/views/anecdotes/_form.html.erb
<%= form_for(@anecdote) do |f| %>
  <% if @anecdote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anecdote.errors.count, "error") %> prohibited this anecdote from being saved:</h2>

      <ul>
      <% @anecdote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sujet %><br>
    <%= f.text_field :sujet %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :texte %><br>
    <%= f.text_area :texte %>
  </div>
  <div class="field">
    <%= f.label :chapitre_id %><br>
    <%= f.number_field :chapitre_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anecdotes/edit.html.erb
<h1>Editing anecdote</h1>

<%= render 'form' %>

<%= link_to 'Show', @anecdote %> |
<%= link_to 'Back', anecdotes_path %>

app/views/anecdotes/index.html.erb
<h1>Liste des annecdotes</h1>

<table>
  <thead>
    <tr>
      <th>Sujet</th>
      <th>Theme</th>
      <th>Texte</th>
      <th>Chapitre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @anecdotes.each do |anecdote| %>
      <tr>
        <td><%= anecdote.sujet %></td>
        <td><%= anecdote.theme %></td>
        <td><%= anecdote.texte %></td>
        <td><%= anecdote.chapitre_id %></td>
        <td><%= link_to 'Voir', anecdote %></td>
        <td><%= link_to 'Modifier', edit_anecdote_path(anecdote) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anecdote', new_anecdote_path %>

app/views/anecdotes/new.html.erb
<h1>New anecdote</h1>

<%= render 'form' %>

<%= link_to 'Back', anecdotes_path %>

app/views/anecdotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sujet:</strong>
  <%= @anecdote.sujet %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @anecdote.theme %>
</p>

<p>
  <strong>Texte:</strong>
  <%= @anecdote.texte %>
</p>

<p>
  <strong>Chapitre:</strong>
  <%= @anecdote.chapitre_id %>
</p>

<%= link_to 'Edit', edit_anecdote_path(@anecdote) %> |
<%= link_to 'Back', anecdotes_path %>