config/routes.rb
ProjetApp::Application.routes.draw do
  get 'home' => 'pages#home' , as: 'home'
  get 'about' => 'pages#about' , as: 'about'
  get 'contact' => 'pages#contact' , as: 'contact'
  get 'aide' => 'pages#aide' , as: 'aide'
 
  
  resources :anecdotes

  resources :personnes

  resources :scenes

  resources :chapitres do
	get 'delete' => 'chapitre#delete' , as: 'delete'
  end
	
 
  
  root to: 'pages#home'
  
  
end

app/models/scene.rb
# == Schema Information
#
# Table name: scenes
#
#  id          :integer          not null, primary key
#  periode     :date
#  lieu        :string(255)
#  recit       :text
#  personne_id :integer
#  chapitre_id :integer
#  numero      :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Scene < ActiveRecord::Base
	belongs_to :chapitre
	has_many :personnes, :dependent => :destroy

	validates :numero, :presence => true,
			   :uniqueness => true
	validates :chapitre_id, :presence => true
	validates :personne_id, :presence => true
	validates :lieu, :presence => true,
			  :length => { :maximum => 30 }
			 
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scene }
      else
        format.html { render action: 'new' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:periode, :lieu, :recit, :personne_id, :chapitre_id, :numero)
    end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :periode %><br>
    <%= f.date_select :periode %>
  </div>
  <div class="field">
    <%= f.label :lieu %><br>
    <%= f.text_field :lieu %>
  </div>
  <div class="field">
    <%= f.label :recit %><br>
    <%= f.text_area :recit %>
  </div>
  <div class="field">
    <%= f.label :personne_id %><br>
    <%= f.number_field :personne_id %>
  </div>
  <div class="field">
    <%= f.label :chapitre_id %><br>
    <%= f.number_field :chapitre_id %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Liste des scenes</h1>

<table>
  <thead>
    <tr>
      <th>Periode</th>
      <th>Lieu</th>
      <th>Recit</th>
      <th>Personne</th>
      <th>Chapitre</th>
      <th>Numero</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.periode %></td>
        <td><%= scene.lieu %></td>
        <td><%= scene.recit %></td>
        <td><%= scene.personne_id %></td>
        <td><%= scene.chapitre_id %></td>
        <td><%= scene.numero %></td>
        <td><%= link_to 'Voir', scene %></td>
        <td><%= link_to 'Modifier', edit_scene_path(scene) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_scene_path %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Periode:</strong>
  <%= @scene.periode %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @scene.lieu %>
</p>

<p>
  <strong>Recit:</strong>
  <%= @scene.recit %>
</p>

<p>
  <strong>Personne:</strong>
  <%= @scene.personne_id %>
</p>

<p>
  <strong>Chapitre:</strong>
  <%= @scene.chapitre_id %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @scene.numero %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>