config/routes.rb
ProjetApp::Application.routes.draw do
  get 'home' => 'pages#home' , as: 'home'
  get 'about' => 'pages#about' , as: 'about'
  get 'contact' => 'pages#contact' , as: 'contact'
  get 'aide' => 'pages#aide' , as: 'aide'
 
  
  resources :anecdotes

  resources :personnes

  resources :scenes

  resources :chapitres do
	get 'delete' => 'chapitre#delete' , as: 'delete'
  end
	
 
  
  root to: 'pages#home'
  
  
end

app/models/chapitre.rb
# == Schema Information
#
# Table name: chapitres
#
#  id         :integer          not null, primary key
#  numero     :integer
#  titre      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Chapitre < ActiveRecord::Base
	has_many :scenes, :dependent => :destroy 
	has_many :anecdotes, :dependent => :destroy

	validates :numero, :presence => true,
			   :uniqueness => true
	validates :titre, :presence => true,
			  :length => { :maximum => 30 },
			  :uniqueness => true
end

app/controllers/chapitre_controller.rb
class ChapitreController < ApplicationController
	def show
    	@user = User.find(params[:id])
  	end

	def create
	end
end

app/controllers/chapitres_controller.rb
class ChapitresController < ApplicationController
  before_action :set_chapitre, only: [:show, :edit, :update, :destroy]

  # GET /chapitres
  # GET /chapitres.json
  def index
    @chapitres = Chapitre.all
  end

  # GET /chapitres/1
  # GET /chapitres/1.json
  def show
	@chapitre = Chapitre.find(params[:id])
  end

  # GET /chapitres/new
  def new
    @chapitre = Chapitre.new
    @titre = "Creation"
  end

  # GET /chapitres/1/edit
  def edit
  end

  # POST /chapitres
  # POST /chapitres.json
  def create
    @chapitre = Chapitre.new(chapitre_params)

    
      if @chapitre.save
        redirect_to @chapitre
      else
	@titre = "Creation"
        render 'new'
      end
    
  end

  # PATCH/PUT /chapitres/1
  # PATCH/PUT /chapitres/1.json
  def update
   
      if @chapitre.update(chapitre_params)
        redirect_to @chapitre
      else
       render 'edit'
      end
    
  end

  # DELETE /chapitres/1
  # DELETE /chapitres/1.json

   def delete     
      @chapitre = chapitre.find(params[:id])
      render 'delete'
   end


  def destroy
    @chapitre = Chapitre.find(params[:id])
    @chapitre.destroy
    redirect_to chapitres_path
    
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapitre
      @chapitre = Chapitre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapitre_params
      params.require(:chapitre).permit(:numero, :titre)
    end
end

app/helpers/chapitre_helper.rb
module ChapitreHelper
end

app/helpers/chapitres_helper.rb
module ChapitresHelper
end

app/views/chapitres/_form.html.erb
<%= form_for(@chapitre) do |f| %>
  <% if @chapitre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapitre.errors.count, "error") %> prohibited this chapitre from being saved:</h2>

      <ul>
      <% @chapitre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapitres/delete.html.erb
<%= form_for(:chapitre, :url => {:action => 'destroy', :id => @chapitre.numero }) do |f| %> 
     <p>Are you sure you want to remove "<%= @chapitre.titre %>"</p>
     <%= submit_tag ("Yes, I am sure")
<% end %>

app/views/chapitres/edit.html.erb
<h1>Editing chapitre</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapitre %> |
<%= link_to 'Back', chapitres_path %>

app/views/chapitres/index.html.erb
<h1>Liste des chapitres</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Titre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chapitres.each do |chapitre| %>
      <tr>
        <td><%= chapitre.numero %></td>
        <td><%= chapitre.titre %></td>
        <td><%= link_to 'Voir', chapitre %></td>
        <td><%= link_to 'Modifier', edit_chapitre_path(chapitre) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapitre', new_chapitre_path %>

app/views/chapitres/new.html.erb
<h1>New chapitre</h1>

<%= form_for(@chapitre) do |f| %>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :titre %><br />
    <%= f.text_field :titre %>
  </div>
  <div class="actions">
    <%= f.submit "Creation" %>
  </div>
  <form action="/chapitres" class="new_chapitre" id="new_chapitre" method="post">

<% end %>

app/views/chapitres/show.html.erb
<table class="chapitre">

  <tr>
     <td class="main">

       <% unless @chapitre.scenes.empty? %>
  	 <table class="scene" summary="Les Scenes du chapitre">
		
	 </table>
	
       <% end %>

	
  	 <table class="personne" summary="Les perssonages lie au chapitre">
		
	 </table>
	
       
      </td>
      <td class="sidebar round">
	<strong>Titre</strong> <%= @chapitre.titre %><br />
	<strong>URL</strong> <%= link_to chapitre_path(@chapitre), @chapitre %><br />
	<strong>Scenes</strong> <%= @chapitre.scenes.count %>
	
	</td>
  </tr>
</table>